apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  
  template:
    metadata:
      labels:
        app: vprodb

    spec:
      containers:
        - name: vprodb
          image: vprofile/vprofiledb
          ports:
            - name: vprodb-port
              containerPort: 3306
          volumeMounts:
            - name: vprodb-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vprofile-secret
                  key: db_pass

      nodeSelector:
        zone: us-east-1a
      volumes:
        - name: vprodb-data
          awsElasticBlockStore:
            volumeID: 
            fsType: ext4
      
      initContainers:
        - name: busy
          image: busybox:latest
          volumeMounts:
            - name: vprodb-data
              mountPath: /var/lib/mysql
          command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found"]
